# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaalin < Formula
  desc "Qaraqalpaq tili ushın CLI vositası — latin↔kirill konvertatsiya, son→so'z"
  homepage "https://github.com/dontbeidle/kaalin-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "aeeec9ddf92d44867aa5d514f94d8237262481a6b443a0b5677004f036084efb"

      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "1948a9b97d1c25f4d7d6ee5c4545da5a612c9d162c1b4822b7a824191eb03651"

      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "1e5faa3aabbdbb6f0d77f64b16b1ba82fd0dd7effa791d807c652b917371ca90"
      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "7311f555413d02ad6d7dfc64665bbe95565dc784a2ce4badff6fe0cce2792c4a"
      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
  end

  test do
    system bin/"kaalin", "version"
  end
end
