# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaalin < Formula
  desc "Qaraqalpaq tili ushın CLI vositası — latin↔kirill konvertatsiya, son→so'z"
  homepage "https://github.com/dontbeidle/kaalin-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "d7f353101ab0279acff47b8ee9d0c332902dd52ee150ee55b6c695ad21996396"

      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "415ce289ed03ddecb0586826a34ff72dd330d052ddae6deadfa181e28da8855c"

      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "02a70f66ac344d8cb84930bd26fe35385dcfca7c45a52ffa8e01ce85b7cd5f57"
      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "37b9ef43e0c1d7fc3ce484d3f80699633a2be25b3763a2f68ce28f65c72e9a4b"
      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
  end

  test do
    system bin/"kaalin", "version"
  end
end
