# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KaalinCli < Formula
  desc "Qaraqalpaq tili ushın CLI vositası — latin↔kirill konvertatsiya, son→so'z"
  homepage "https://github.com/dontbeidle/kaalin-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "40dc6bee10958250dd9753f6d15965adacec15224b78c25f92d687c8c43f0b06"

      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "4d90c63e55a93a95f8f89eed7336b63eae2feb7bd10656fd0c3d1e5974fa97ef"

      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "7af0eca152855928e56f24f1ed8b5d2e1f5bbc2e07745b1be6dbe54d2b9d627f"
      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dontbeidle/kaalin-cli/releases/download/v0.1.0/kaalin-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "d1874408de5d63f72b0451551d21830dbc8ad15caa330a89d2ed911e6c282f90"
      define_method(:install) do
        bin.install "kaalin"
        generate_completions_from_executable(bin/"kaalin", "completion")
      end
    end
  end

  test do
    system bin/"kaalin", "version"
  end
end
